### ISSUE TITLE
It doesn't look nice.

### ISSUE THREAD

**Issue by rocketmaster** [schnabear/drrr-like-chat#1]
My site doesn't look nice. And, how do i make permarooms?

**Comment by schnabear** [comment]
Modify the styles (css/style.css) if you want a different type of design. Permanent rooms are not supported (1.0.3 - 1.0.4), you may fork this repository and update it to suit your needs.

**Comment by rocketmaster** [comment]
I tried Bluelover's version of DLC, and i kept getting a blank page. I had a panic attack later, and i nearly tore my hair oiut. What did i do wrong? Or, that guy doesn't know how to code.

**Comment by schnabear** [comment]
Actually the current version of bluelovers' DLC needs zend. If you want to use his version which doesn't use zend, download develop/git/1 branch and fix the following:
- trust_path/template/create_room.default.php [Line 10] change <?php echo Dura::getUrl(); ?> to #
- trust_path/class/user.php [Line 52+] add $this->password_room = null;
- setting.dist.php

If you are using PHP 5.3 you'll encounter an error about asXML override compatibility.

The issue or concerns you are experiencing (bluelovers' DLC) should be posted at his repository.
