### ISSUE TITLE
1.0.3 PHP Error

### ISSUE THREAD

**Issue by chubzwub** [schnabear/drrr-like-chat#2]
PHP Strict Standards:  Declaration of Dura_Class_Xml::asXML() should be compatible with SimpleXMLElement::asXML($filename = NULL) in /home/******/public_html/1.0.3/trust_path/class/xml.php on line 59

Why an error on 1.0.3
?

**Comment by schnabear** [comment]
It's due to error_reporting value set at your php.ini and probably your using PHP 5.3. You can fix it by updating the ini file or by rewriting the overrided method of asXML.

**Comment by schnabear** [comment]
Fixed at 1.0.4 branch, thank you.
